#!/usr/bin/env bash
# =============================================================================
# setup-self-hosted-fonts.sh
# Run ONCE on the VPS (or locally with node) to download Instrument Sans + Syne
# woff2 files and generate a self-hosted fonts.css.
#
# After running:
#   1. Deploy /assets/fonts/ + /css/fonts.css to the VPS
#   2. In every *.html, replace the Google Fonts <link> block with:
#        <link rel="stylesheet" href="css/fonts.css" />
#      (already blocking is fine — it's now served from your own origin, no DNS lookup)
#   3. Remove the two <link rel="preconnect" href="https://fonts.googleapis.com">
#      and <link rel="preconnect" href="https://fonts.gstatic.com"> lines
#   4. Keep the two <link rel="preload" href="assets/fonts/...woff2"> lines
#      BUT update their hrefs to point to /assets/fonts/ (see paths generated below)
#
# Usage: bash scripts/setup-self-hosted-fonts.sh
# Requirements: curl, woff2 URLs must be reachable
# =============================================================================

set -euo pipefail

FONTS_DIR="assets/fonts"
CSS_OUT="css/fonts.css"
mkdir -p "$FONTS_DIR"

echo "Downloading Syne woff2 files..."

# ── Syne weights used: 400 500 600 700 800 ────────────────────────────────────
# URLs sourced from the Google Fonts CSS for display=swap + latin subset.
# Run once; font files are stable per version tag (v24).
declare -A SYNE=(
  ["syne-400"]="https://fonts.gstatic.com/s/syne/v24/8vIH7w4qzmVxm2BL9A.woff2"
  ["syne-500"]="https://fonts.gstatic.com/s/syne/v24/8vIJ7w4qzmVxm2BR-Q.woff2"
  ["syne-600"]="https://fonts.gstatic.com/s/syne/v24/8vIJ7w4qzmVxm2BRpRA.woff2"
  ["syne-700"]="https://fonts.gstatic.com/s/syne/v24/8vIJ7w4qzmVxm2BR0hA.woff2"
  ["syne-800"]="https://fonts.gstatic.com/s/syne/v24/8vIJ7w4qzmVxm2BRvBA.woff2"
)

for name in "${!SYNE[@]}"; do
  url="${SYNE[$name]}"
  out="$FONTS_DIR/${name}.woff2"
  if [ ! -f "$out" ]; then
    curl -sSL "$url" -o "$out"
    echo "  ✓ $out"
  else
    echo "  ↷ $out (exists)"
  fi
done

echo ""
echo "Downloading Instrument Sans woff2 files..."

# ── Instrument Sans weights used: 400 500 600 700 italic-400 ─────────────────
# woff2 URLs: latin subset from Google Fonts CSS (v4). Upright = pxiTypc9..., Italic = pxiDypc9...
declare -A ISANS=(
  ["instrument-sans-400"]="https://fonts.gstatic.com/s/instrumentsans/v4/pxiTypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr0SZe1Q.woff2"
  ["instrument-sans-500"]="https://fonts.gstatic.com/s/instrumentsans/v4/pxiTypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-iZe1Q.woff2"
  ["instrument-sans-600"]="https://fonts.gstatic.com/s/instrumentsans/v4/pxiTypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnrFiFe1Q.woff2"
  ["instrument-sans-700"]="https://fonts.gstatic.com/s/instrumentsans/v4/pxiTypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnrPiFe1Q.woff2"
  ["instrument-sans-400i"]="https://fonts.gstatic.com/s/instrumentsans/v4/pxiDypc9vsFDm051Uf6KVwgkfoSxQ0GsTpmZvfJimInkSBGe1Q.woff2"
)

for name in "${!ISANS[@]}"; do
  url="${ISANS[$name]}"
  out="$FONTS_DIR/${name}.woff2"
  if [ ! -f "$out" ]; then
    curl -sSL "$url" -o "$out"
    echo "  ✓ $out"
  else
    echo "  ↷ $out (exists)"
  fi
done

echo ""
echo "Generating $CSS_OUT ..."

cat > "$CSS_OUT" << 'EOCSS'
/*
 * Self-hosted fonts — generated by scripts/setup-self-hosted-fonts.sh
 * Replaces the Google Fonts CDN dependency entirely.
 * font-display: swap prevents render-blocking; text still shows in fallback font
 * until the woff2 is downloaded (which is preloaded in <head>).
 */

/* ── Syne ───────────────────────────────────────────────────────────────────── */
@font-face {
  font-family: 'Syne';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('../assets/fonts/syne-400.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Syne';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('../assets/fonts/syne-500.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Syne';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('../assets/fonts/syne-600.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Syne';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('../assets/fonts/syne-700.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Syne';
  font-style: normal;
  font-weight: 800;
  font-display: swap;
  src: url('../assets/fonts/syne-800.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}

/* ── Instrument Sans ─────────────────────────────────────────────────────────── */
@font-face {
  font-family: 'Instrument Sans';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('../assets/fonts/instrument-sans-400.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Instrument Sans';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('../assets/fonts/instrument-sans-500.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Instrument Sans';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('../assets/fonts/instrument-sans-600.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Instrument Sans';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('../assets/fonts/instrument-sans-700.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Instrument Sans';
  font-style: italic;
  font-weight: 400;
  font-display: swap;
  src: url('../assets/fonts/instrument-sans-400i.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC,
                 U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
                 U+2212, U+2215, U+FEFF, U+FFFD;
}
EOCSS

echo "  ✓ $CSS_OUT"
echo ""
echo "════════════════════════════════════════════════════════"
echo " NEXT STEPS (run after this script succeeds):"
echo "════════════════════════════════════════════════════════"
echo ""
echo " 1. Deploy updated files to VPS:"
echo "    rsync -az assets/fonts/ user@vps:/var/www/html/assets/fonts/"
echo "    rsync -az css/fonts.css  user@vps:/var/www/html/css/fonts.css"
echo ""
echo " 2. Run the HTML patch script:"
echo "    node scripts/patch-google-fonts-to-local.mjs"
echo "    (this replaces the <link> blocks in all *.html files)"
echo ""
echo " 3. Deploy updated HTML:"
echo "    rsync -az *.html user@vps:/var/www/html/"
echo ""
echo " 4. Pre-compress assets on VPS for gzip_static / brotli_static:"
echo "    bash scripts/compress-assets.sh"
echo ""
echo "Done."
