# -*- coding: utf-8 -*-
"""Additional service page configs (SEO, Brand, CMS, Analytics)."""
from __future__ import annotations

IMG_KOVA = "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&amp;fit=crop&amp;w=800&amp;h=500&amp;q=80"
IMG_LUMA = "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&amp;fit=crop&amp;w=800&amp;h=500&amp;q=80"
IMG_MERO = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&amp;fit=crop&amp;w=800&amp;h=500&amp;q=80"

MORE_PAGES: list[dict] = [
    {
        "file": "service-seo-growth.html",
        "service_name": "SEO & Growth",
        "title": "SEO &amp; Growth Services — CraftedPixel | Technical SEO, Content &amp; Migrations",
        "og_title": "SEO &amp; Organic Growth Services | CraftedPixel",
        "meta_desc": "Technical SEO audits, on-page optimization, site migrations with redirect mapping, Google Search Console, and growth experiments. CraftedPixel helps B2B and e-commerce sites earn durable organic traffic.",
        "crumb_last": "SEO &amp; growth",
        "h1": "SEO &amp; Growth",
        "lede": "Organic traffic that compounds—crawl health, intent-led content structure, and migrations that preserve equity instead of torching it.",
        "meta_row": [
            ("Engagements", "Audits to retainers"),
            ("Focus", "Technical · On-page · GSC"),
            ("Output", "Playbooks + dashboards"),
        ],
        "jump": [
            ("#process-flow", "Process"),
            ("#technical", "Technical"),
            ("#onpage", "On-page"),
            ("#migrations", "Migrations"),
            ("#measurement", "GSC"),
            ("#growth", "Growth"),
            ("#future", "Future"),
            ("#related-work", "Work"),
            ("#service-faq", "FAQ"),
        ],
        "intro_h": "How we plug in",
        "intro_lede": "We pair search-engine reality with your editorial capacity—no vanity keyword lists, no black-hat shortcuts. You get prioritized fixes, clear owners, and reporting tied to pages that actually drive revenue or pipeline.",
        "pills": [
            ("fa-magnifying-glass-chart", "<strong>Technical foundation</strong> — crawl, indexation, Core Web Vitals, and schema where it earns clicks."),
            ("fa-pen-to-square", "<strong>Content &amp; IA</strong> — briefs, internal links, and templates editors can sustain."),
            ("fa-route", "<strong>Migration guardrails</strong> — redirects, testing, and monitoring when URLs or platforms change."),
        ],
        "flow_h": "From crawl clarity to compounding traffic",
        "flow_lede": "Each step produces artifacts your team can execute—briefs, tickets, or dashboards—not a one-off PDF.",
        "flow_steps": [
            ("fa-spider", "Crawl", "Index health"),
            ("fa-file-lines", "On-page", "Intent &amp; IA"),
            ("fa-shuffle", "Migrate", "301 maps"),
            ("fa-chart-line", "Measure", "GSC &amp; KPIs"),
            ("fa-flask", "Test", "Snippets &amp; LP"),
        ],
        "flow_strip": ["Screaming Frog", "GSC", "Schema", "Briefs", "Looker"],
        "sections": [
            {
                "id": "technical",
                "num": "01",
                "title": "Technical SEO",
                "aria": "sd-seo-tech-title",
                "tag": "Crawl budget, indexation, canonicals, XML sitemaps, and structured data—foundation work that lets Google trust what you publish.",
                "p1": "We audit like engineers: log analysis hints, render parity, and duplicate URL patterns that quietly split signals. Fixes land as tickets with severity, effort, and expected impact—not a 200-slide deck.",
                "p2": "Core Web Vitals and mobile usability tie directly to rankings and CRO; we align with your dev backlog so perf wins don&rsquo;t stall in &ldquo;nice to have.&rdquo;",
                "outs": [
                    "Prioritized technical backlog with owners",
                    "Robots, sitemap, and canonical recommendations",
                    "Schema plan (Article, Product, FAQ where valid)",
                    "Pre/post deploy checklist for releases",
                ],
                "note": "Traffic flatlined after a replatform, staging leaks to index, or GSC shows persistent coverage errors.",
            },
            {
                "id": "onpage",
                "num": "02",
                "title": "On-page &amp; content SEO",
                "aria": "sd-seo-onpage-title",
                "tag": "Intent mapping, heading hierarchy, internal links, and editor-friendly briefs—so new pages rank without reinventing the wheel each time.",
                "p1": "We group queries by intent, map them to URL patterns, and define template-level rules (titles, meta, body structure) your CMS can enforce.",
                "p2": "When you lack volume, we focus on bottom-funnel and comparison content first—where conversions justify the investment.",
                "outs": [
                    "Keyword / intent map tied to templates",
                    "Content brief templates &amp; exemplars",
                    "Internal link recommendations",
                    "Editor checklist for publish QA",
                ],
                "note": "Editorial teams ship fast but pages compete with each other, or thin templates dilute topical authority.",
            },
            {
                "id": "migrations",
                "num": "03",
                "title": "Migrations &amp; redirects",
                "aria": "sd-seo-mig-title",
                "tag": "Domain, subdomain, or CMS moves with 1:1 mapping, staged testing, and post-launch monitoring—so equity and backlinks transfer cleanly.",
                "p1": "We inventory URLs, backlinks, and traffic drivers before cutover; redirect rules are tested in staging with sample old→new pairs.",
                "p2": "After launch we watch GSC coverage, server logs, and ranked URL sets—rolling back or patching rules before losses harden.",
                "outs": [
                    "Redirect map (CSV) + edge-case rules",
                    "Pre-launch crawl diff report",
                    "Post-launch 7/30-day monitoring plan",
                    "Stakeholder comms template for URL changes",
                ],
                "note": "Rebrand, HTTPS cutover, headless move, or merger integration where organic is a board-level KPI.",
            },
            {
                "id": "measurement",
                "num": "04",
                "title": "Measurement &amp; Search Console",
                "aria": "sd-seo-gsc-title",
                "tag": "GSC hygiene, query–page monitoring, and dashboards that connect rankings to landing engagement—not just green arrows in a slide.",
                "p1": "We segment branded vs. non-branded, track striking distance terms, and flag anomalies (CTR cliffs, sudden impression drops) with likely causes.",
                "p2": "Where useful we connect GA4 landing engagement and conversion paths so SEO prioritization respects revenue—not only clicks.",
                "outs": [
                    "GSC property cleanup &amp; user access model",
                    "Monthly or weekly scorecard template",
                    "Alert thresholds for coverage &amp; CWV",
                    "Annotation log for releases &amp; migrations",
                ],
                "note": "Leadership wants an organic KPI you can defend, or marketing lost trust in last agency&rsquo;s opaque reporting.",
            },
            {
                "id": "growth",
                "num": "05",
                "title": "Growth experiments",
                "aria": "sd-seo-growth-title",
                "tag": "Hypothesis-led title/meta tests, snippet tuning, and landing variants—small bets with readouts tied to CTR, CVR, or qualified leads.",
                "p1": "We document a hypothesis, success metric, and minimum sample before changing live pages—avoiding endless tweak loops.",
                "p2": "Experiments pair with analytics events so you learn even when the headline test is flat.",
                "outs": [
                    "Experiment backlog with ICE scoring",
                    "Before/after SERP capture where applicable",
                    "Template for scaling winners across URLs",
                    "Guardrails so tests don&rsquo;t cannibalize brand",
                ],
                "note": "You have traffic but weak CTR, or landing pages match queries poorly once users arrive.",
            },
        ],
        "quote": (
            "They stopped our migration from nuking a decade of blog equity—redirect testing alone paid for the engagement.",
            "Sam T.",
            "Head of Marketing, B2B SaaS",
        ),
        "future_cards": [
            ("Piloting", "AI-assisted content outlines", "Brief scaffolding from SERP features and competitor gaps—edited by humans for tone and accuracy."),
            ("Exploring", "International hreflang kits", "Locale matrices with copy expansion rules so hreflang doesn&rsquo;t silently break."),
            ("Coming soon", "SGE / AI overview monitoring", "Tracking how generative summaries shift CTR by vertical."),
            ("Exploring", "Product-led SEO templates", "PLG sites where docs and changelog pages compete for high-intent queries."),
        ],
        "related_lede": "Organic and CRO wins from recent launches—full narratives on the homepage.",
        "related_cards": [
            {
                "href": "index.html#case-luma",
                "img": IMG_LUMA,
                "title": "Luma — DTC storefront",
                "desc": "Quiz funnel and PDP work with <strong>2× conversion</strong> vs. baseline—SEO-friendly structure.",
            },
            {
                "href": "index.html#case-kova",
                "img": IMG_KOVA,
                "title": "Kova — SaaS platform",
                "desc": "Information architecture and recruiter flows supporting organic landing pages.",
            },
        ],
        "cadence_lede": "Typical cadence for an audit or migration track—parallel to your release train.",
        "cadence_w1": [
            "Access: GSC, GA4, CMS, and staging",
            "Baseline crawl + indexation snapshot",
            "Stakeholder sync on goals &amp; constraints",
        ],
        "cadence_w2": [
            "Prioritized backlog workshop",
            "First implementation batch (dev or content)",
            "Scorecard v1 + monitoring hooks",
        ],
        "cadence_need": [
            "Search Console verified property",
            "List of markets / languages if international",
            "Editorial calendar or capacity estimate",
            "Engineering point person for technical tickets",
        ],
        "fit_p": "If the site doesn&rsquo;t exist yet or performance is critically broken, pairing SEO with web development or UI/UX often yields faster wins.",
        "fit_links": [
            ("service-web-development.html", "Web development — performance, rendering, and platform fixes"),
            ("service-content-cms.html", "Content &amp; CMS — modeling and publishing workflows that scale SEO"),
            ("service-ui-ux.html", "UI/UX — when CRO and usability block conversion from organic traffic"),
        ],
        "faq_topic": "SEO &amp; growth engagements",
        "faq_intro": "What we need, what we won&rsquo;t promise, and how we work with your dev and content teams.",
        "faq_items": [
            (
                "Do you guarantee rankings?",
                "No ethical team should. We guarantee disciplined execution: technical fixes, measured experiments, and reporting you can audit. Rankings follow quality and competition—we show the work behind the trend lines.",
            ),
            (
                "How long until we see results?",
                "Technical fixes can move the needle in weeks; content compounding often needs quarters. We set expectations per tactic in the first two weeks so finance and leadership hear realistic ranges.",
            ),
            (
                "Can you work with our agency or in-house SEO?",
                "Yes. We can own a workstream (e.g., migrations) or augment your team with audits and QA. Clear RACI up front prevents duplicate effort.",
            ),
            (
                "What tools do you require?",
                "At minimum GSC and analytics access. We often use crawler exports you can run in-house if licensing is sensitive—workflow adapts to your policy.",
            ),
            (
                "Do you build links?",
                "We focus on earned mentions and content worth citing—not paid link networks. If digital PR is in scope, we coordinate with partners or your PR team.",
            ),
        ],
        "cta_p": "Tell us your URL, timeline, and whether you&rsquo;re pre- or post-migration—we&rsquo;ll recommend audit depth or ongoing rhythm.",
        "back_href": "services.html#seo-growth",
        "back_label": "SEO offerings list",
    },
    {
        "file": "service-brand-design-systems.html",
        "service_name": "Brand & design systems",
        "title": "Brand &amp; Design System Services — CraftedPixel | Identity, Tokens &amp; Components",
        "og_title": "Brand Identity &amp; Design Systems | CraftedPixel",
        "meta_desc": "Logo and visual identity, scalable design systems, Figma component libraries, and practical brand guidelines. Align marketing and product surfaces with CraftedPixel.",
        "crumb_last": "Brand &amp; systems",
        "h1": "Brand &amp; design systems",
        "lede": "Identity, guidelines, and component libraries that scale—so marketing sites and product UI feel like one company, not two brands that met once.",
        "meta_row": [
            ("Engagements", "Identity to system rollout"),
            ("Deliverables", "Figma · Tokens · Docs"),
            ("Output", "Guidelines + kit"),
        ],
        "jump": [
            ("#process-flow", "Process"),
            ("#identity", "Identity"),
            ("#design-systems", "Systems"),
            ("#components", "Components"),
            ("#guidelines", "Guidelines"),
            ("#future", "Future"),
            ("#related-work", "Work"),
            ("#service-faq", "FAQ"),
        ],
        "intro_h": "How we plug in",
        "intro_lede": "We connect narrative, visual language, and implementation constraints early—so your first landing page and your fiftieth product screen share tokens, type scales, and motion rules that engineers can adopt.",
        "pills": [
            ("fa-pen-nib", "<strong>Identity sprint</strong> — mark, color, type, and voice starters for launch deadlines."),
            ("fa-layer-group", "<strong>System program</strong> — tokens, components, and docs across web + product."),
            ("fa-book-open", "<strong>Guidelines refresh</strong> — tame drift: consolidate rules editors and devs will follow."),
        ],
        "flow_h": "From story to shipped surfaces",
        "flow_lede": "Brand isn&rsquo;t a PDF—it&rsquo;s decisions that repeat in Figma and code.",
        "flow_steps": [
            ("fa-lightbulb", "Narrative", "Position &amp; voice"),
            ("fa-swatchbook", "System", "Tokens &amp; type"),
            ("fa-cubes", "Library", "Components"),
            ("fa-book", "Guidelines", "Usage &amp; templates"),
        ],
        "flow_strip": ["Logo", "Color", "Type", "Grid", "Motion"],
        "sections": [
            {
                "id": "identity",
                "num": "01",
                "title": "Logo &amp; visual identity",
                "aria": "sd-brand-id-title",
                "tag": "Marks, color systems, typography, and usage rules tested on real touchpoints—favicons, app icons, slide decks, and social—not only a hero mockup.",
                "p1": "We explore positioning tension first: who you are for, who you are not for, and the few attributes you want recalled. Visual directions are scored against accessibility, motion, and production constraints.",
                "p2": "Deliverables include master artwork, safe zones, minimum sizes, and monochrome / reversed treatments so partners don&rsquo;t improvise under pressure.",
                "outs": [
                    "Logo suite (SVG, PNG, app icon exports)",
                    "Color ramps with contrast pairs (WCAG-aware)",
                    "Primary &amp; secondary type stacks with fallbacks",
                    "Competitive differentiation notes",
                ],
                "note": "Funding milestone, rebrand after M&amp;A, or your Series A story outgrew the bootstrap mark.",
            },
            {
                "id": "design-systems",
                "num": "02",
                "title": "Design systems",
                "aria": "sd-brand-ds-title",
                "tag": "Semantic tokens, spacing scales, elevation, and naming conventions that map cleanly to CSS variables or platform themes.",
                "p1": "We define primitives then semantic aliases (e.g., surface.default, text.muted) so redesigns don&rsquo;t require renaming every component.",
                "p2": "Documentation covers contribution, versioning, and deprecation—so the system survives your next hire spike.",
                "outs": [
                    "Token table (JSON / Style Dictionary–ready)",
                    "Theming notes (light/dark, brand accents)",
                    "Component taxonomy &amp; status model",
                    "Governance outline for proposals &amp; reviews",
                ],
                "note": "Product and marketing diverged; every screen invents new grays and radii.",
            },
            {
                "id": "components",
                "num": "03",
                "title": "Component libraries",
                "aria": "sd-brand-comp-title",
                "tag": "Figma kits and coded counterparts with props, variants, and states that match how engineers actually compose screens.",
                "p1": "We align on atomic vs. composite boundaries, slot patterns for marketing vs. product, and how content editors will stress each component.",
                "p2": "When Storybook or similar is in play, we mirror naming and default props so design QA has a single checklist.",
                "outs": [
                    "Figma library with variants &amp; docs",
                    "Starter coded components (scope-dependent)",
                    "Interaction &amp; motion specs for key patterns",
                    "QA checklist for new contributions",
                ],
                "note": "Engineers rebuild the same buttons and cards because the library never shipped—or drifted from Figma.",
            },
            {
                "id": "guidelines",
                "num": "04",
                "title": "Brand guidelines &amp; templates",
                "aria": "sd-brand-guide-title",
                "tag": "Slide, social, and email patterns with do/don&rsquo;t examples—short enough that teams open them weekly.",
                "p1": "We prioritize scenarios your team repeats: pitch decks, changelog posts, hiring banners, and partner co-mark. Each gets a template, not a paragraph of adjectives.",
                "p2": "Optional Notion or microsite format so search and updates beat the frozen PDF problem.",
                "outs": [
                    "Guidelines site or PDF (your workflow)",
                    "Template files (Figma / Slides / email HTML as scoped)",
                    "Voice &amp; tone examples with before/after",
                    "Asset download hub structure",
                ],
                "note": "Distributed teams freestyle brand on every campaign; legal or partners ask for official rules.",
            },
        ],
        "quote": (
            "For the first time marketing and product both pull from the same token set—our slides finally match the app.",
            "Priya K.",
            "Creative Director, Fintech",
        ),
        "future_cards": [
            ("Piloting", "Brand ops office hours", "Monthly office hours for campaign reviews against system rules."),
            ("Exploring", "Multi-brand architecture", "Parent / sub-brand token strategies for portfolios."),
            ("Coming soon", "AI-assisted naming QA", "Lint marketing copy against banned claims and voice rules—human approval required."),
            ("Exploring", "Design–code drift audits", "Quarterly diff between Figma library and Storybook props."),
        ],
        "related_lede": "Brand and product design showing up together in shipped work.",
        "related_cards": [
            {
                "href": "index.html#case-mero",
                "img": IMG_MERO,
                "title": "Mero — fintech app",
                "desc": "Product design <strong>plus brand</strong> before full-stack ship.",
            },
            {
                "href": "index.html#case-luma",
                "img": IMG_LUMA,
                "title": "Luma — DTC brand",
                "desc": "Storefront and quiz experience with cohesive visual language.",
            },
        ],
        "cadence_lede": "Identity and system work broken into reviewable milestones.",
        "cadence_w1": [
            "Stakeholder interviews &amp; competitive scan",
            "Creative directions (mood + rationale)",
            "Shortlist direction with usage tests",
        ],
        "cadence_w2": [
            "Refine master assets &amp; color/type ramps",
            "Seed token set + first 5 components",
            "Guidelines outline for templates",
        ],
        "cadence_need": [
            "Decision-makers available for consolidated feedback",
            "Any existing brand assets or legal trademark constraints",
            "Target surfaces (web, iOS, slide, etc.)",
            "Engineering contact for token import path",
        ],
        "fit_p": "If you need full UI flows or research before the brand stabilizes, UI/UX discovery may run ahead of or alongside identity.",
        "fit_links": [
            ("service-ui-ux.html", "UI/UX — journeys, prototyping, and research"),
            ("service-web-development.html", "Web development — implementing tokens and components in production"),
            ("service-content-cms.html", "Content &amp; CMS — templates editors use daily"),
        ],
        "faq_topic": "Brand &amp; system engagements",
        "faq_intro": "Ownership, file formats, and how we collaborate with your marketing and engineering leads.",
        "faq_items": [
            (
                "Who owns the final files?",
                "You do. We deliver source files and export packages under your agreement; no hidden licensing traps on your own mark.",
            ),
            (
                "Can you extend our existing system?",
                "Yes. We audit what&rsquo;s working, deprecate duplicates, and add components or tokens with migration notes for product teams.",
            ),
            (
                "How do you handle fonts and licensing?",
                "We flag commercial vs. self-hosted needs up front and document fallbacks. Final licensing sits with your procurement.",
            ),
            (
                "What if we only need guidelines, not a full rebrand?",
                "We can codify what you already have—tightening rules, templates, and examples without touching the logo.",
            ),
            (
                "Do you name the company or product?",
                "Naming can be in scope as a facilitated sprint; we pair linguistic checks with domain and trademark sanity where you involve counsel.",
            ),
        ],
        "cta_p": "Share where brand feels broken today—slides, product, or partner channels—and we&rsquo;ll propose identity, system, or guidelines depth accordingly.",
        "back_href": "services.html#brand-design-systems",
        "back_label": "Brand offerings list",
    },
    {
        "file": "service-content-cms.html",
        "service_name": "Content & CMS",
        "title": "Content &amp; CMS Services — CraftedPixel | Headless CMS, WordPress &amp; Migrations",
        "og_title": "Content Strategy, CMS &amp; Migrations | CraftedPixel",
        "meta_desc": "Content modeling, headless CMS with previews, WordPress block authoring, content migrations with URL mapping, and editorial governance. Ship pages without a ticket per comma.",
        "crumb_last": "Content &amp; CMS",
        "h1": "Content &amp; CMS",
        "lede": "Structured content, sane authoring workflows, and migrations that preserve URLs and assets—so marketing ships without engineering becoming a bottleneck.",
        "meta_row": [
            ("Engagements", "Modeling to migration"),
            ("Platforms", "Sanity · Contentful · WP"),
            ("Output", "Schema + playbooks"),
        ],
        "jump": [
            ("#process-flow", "Process"),
            ("#modeling", "Modeling"),
            ("#headless", "Headless"),
            ("#wordpress-cms", "WordPress"),
            ("#content-migrations", "Migrations"),
            ("#governance", "Governance"),
            ("#future", "Future"),
            ("#related-work", "Work"),
            ("#service-faq", "FAQ"),
        ],
        "intro_h": "How we plug in",
        "intro_lede": "We design content types around how editors think and how the frontend consumes data—then wire previews, roles, and validation so mistakes surface before publish, not after social goes live.",
        "pills": [
            ("fa-diagram-project", "<strong>Model &amp; build</strong> — new CMS or headless stack with editor-friendly fields."),
            ("fa-right-left", "<strong>Migration</strong> — ETL-style moves with URL and asset integrity."),
            ("fa-chalkboard-user", "<strong>Train &amp; govern</strong> — playbooks so quality holds after handoff."),
        ],
        "flow_h": "From model to confident publishing",
        "flow_lede": "Editors get guardrails; developers get typed content contracts.",
        "flow_steps": [
            ("fa-sitemap", "Model", "Types &amp; fields"),
            ("fa-cloud", "Headless", "API &amp; preview"),
            ("fa-wordpress", "WP", "Blocks &amp; roles"),
            ("fa-truck-ramp-box", "Migrate", "URLs &amp; assets"),
            ("fa-clipboard-check", "Govern", "QA &amp; training"),
        ],
        "flow_strip": ["Schema", "Preview", "Webhooks", "Roles", "Lint"],
        "sections": [
            {
                "id": "modeling",
                "num": "01",
                "title": "Content strategy &amp; modeling",
                "aria": "sd-cms-model-title",
                "tag": "Content types, relationships, and validation rules that reflect publishing cadence—not a generic blog post template for everything.",
                "p1": "We interview editors and map recurring campaigns, localization, and legal needs before naming fields. Optional fields and defaults are chosen to reduce publish friction.",
                "p2": "SEO and analytics hooks are designed in: canonical fields, structured data inputs, and UTM discipline where helpful.",
                "outs": [
                    "Entity-relationship style content map",
                    "Field-level definitions &amp; help text",
                    "Role matrix (who can publish vs. schedule)",
                    "Sample entries for QA",
                ],
                "note": "Editors fight the CMS daily, or the marketing site can&rsquo;t represent your real product surface area.",
            },
            {
                "id": "headless",
                "num": "02",
                "title": "Headless CMS",
                "aria": "sd-cms-headless-title",
                "tag": "API-first content with preview URLs, webhook-driven revalidation, and fallbacks when the API hiccups—so static performance doesn&rsquo;t blind editors.",
                "p1": "We align webhook payloads with your frontend cache strategy (ISR, edge, or classic builds) and document failure modes.",
                "p2": "Draft workflows and scheduled publishes get first-class treatment—not bolted on after launch.",
                "outs": [
                    "Content API schema export",
                    "Preview &amp; production environment map",
                    "Webhook / revalidation checklist",
                    "SDK or query examples for your stack",
                ],
                "note": "You chose Next.js or similar and need editorial parity with a decoupled CMS.",
            },
            {
                "id": "wordpress-cms",
                "num": "03",
                "title": "WordPress authoring",
                "aria": "sd-cms-wp-title",
                "tag": "Block themes, patterns, and capabilities tailored to your team—without plugin soup that breaks every PHP upgrade.",
                "p1": "We constrain patterns to what you need, register ACF or block attributes thoughtfully, and separate global styles from per-post overrides.",
                "p2": "Roles and revisions are configured so freelancers can&rsquo;t accidentally ship to prod.",
                "outs": [
                    "Theme or child theme plan",
                    "Block pattern library",
                    "Editor training video or live session",
                    "Update &amp; backup runbook",
                ],
                "note": "Marketing owns WordPress today but velocity dropped as custom fields multiplied.",
            },
            {
                "id": "content-migrations",
                "num": "04",
                "title": "Content migrations",
                "aria": "sd-cms-mig-title",
                "tag": "Scripts and spot-checks for HTML cleanup, asset relocation, and slug preservation—paired with SEO redirect plans when URLs must change.",
                "p1": "We sample edge cases early: tables, embeds, internal links, and shortcodes from the legacy stack.",
                "p2": "Rollback and delta migration paths are documented for large corp sites with ongoing publishes.",
                "outs": [
                    "Migration runbook &amp; dry-run report",
                    "Asset URL mapping",
                    "Validation queries / scripts",
                    "Post-migration content QA checklist",
                ],
                "note": "Replatforming from Drupal, Contentful, or static exports with thousands of entries.",
            },
            {
                "id": "governance",
                "num": "05",
                "title": "Training &amp; governance",
                "aria": "sd-cms-gov-title",
                "tag": "Short playbooks, office hours, and lint rules—so quality doesn&rsquo;t depend on one heroic PM.",
                "p1": "We produce quick-reference cards for common tasks: new landing, campaign swap, legal disclaimer update.",
                "p2": "Optional automated checks: broken links, required alt text, or schema completeness before publish.",
                "outs": [
                    "Editor handbook (Notion or PDF)",
                    "Office hours plan (if retained)",
                    "Publishing checklist",
                    "Escalation path to engineering",
                ],
                "note": "You launched a new CMS but adoption stalled; teams revert to Google Docs + copy-paste.",
            },
        ],
        "quote": (
            "Editors stopped Slack-bombing engineers for every hero swap—preview and roles finally match how we work.",
            "Chris L.",
            "Director of Content, B2B",
        ),
        "future_cards": [
            ("Piloting", "Structured content linting", "Pre-publish checks for broken references and required SEO fields."),
            ("Exploring", "AI assist for alt text", "Suggestions with human approval and brand tone guardrails."),
            ("Coming soon", "Multi-repo preview orchestration", "Coordinated previews when marketing and product content intersect."),
            ("Exploring", "Localization workflows", "Field-level translation states without duplicate posts."),
        ],
        "related_lede": "Projects where content velocity and engineering handoff both mattered.",
        "related_cards": [
            {
                "href": "index.html#case-luma",
                "img": IMG_LUMA,
                "title": "Luma — commerce content",
                "desc": "Shopify Plus + content-heavy merchandising flows.",
            },
            {
                "href": "index.html#case-kova",
                "img": IMG_KOVA,
                "title": "Kova — product marketing",
                "desc": "Complex product surfaces with editor-friendly patterns.",
            },
        ],
        "cadence_lede": "Modeling and migration projects in two-week slices.",
        "cadence_w1": [
            "Editor shadowing &amp; legacy pain inventory",
            "Draft content model v0",
            "Align preview &amp; webhook approach with eng",
        ],
        "cadence_w2": [
            "Model v1 in CMS + seed content",
            "Migration dry run on sample set",
            "Training draft &amp; FAQ",
        ],
        "cadence_need": [
            "CMS vendor decision or shortlist",
            "Sanitized content export or API access",
            "SEO owner for URL strategy",
            "Staging environment for preview testing",
        ],
        "fit_p": "If rendering performance or front-end architecture is the blocker before CMS choice, web development discovery may run in parallel.",
        "fit_links": [
            ("service-web-development.html", "Web development — frontend that consumes headless APIs"),
            ("service-seo-growth.html", "SEO &amp; growth — URL and IA implications of migrations"),
            ("service-ui-ux.html", "UI/UX — templates and components editors will live in"),
        ],
        "faq_topic": "Content &amp; CMS engagements",
        "faq_intro": "Platforms we touch, migration risk, and how editors stay unblocked.",
        "faq_items": [
            (
                "Which CMS do you recommend?",
                "We match stack to editorial workflow, developer skill, and compliance—not a single vendor kickback. We&rsquo;ll document tradeoffs and a decision memo.",
            ),
            (
                "Can you migrate without downtime?",
                "We plan cutovers with DNS, caching, and content freeze windows. Zero-downtime depends on architecture—we set honest expectations per platform.",
            ),
            (
                "How do previews work headlessly?",
                "Draft tokens, secure preview hosts, and webhook-triggered builds or edge revalidation—editors see changes before go-live.",
            ),
            (
                "Will you train non-technical editors?",
                "Yes. Live sessions plus async docs are standard; we tune depth to your team&rsquo;s comfort.",
            ),
            (
                "What about PII in content?",
                "We flag fields that must not hit public APIs, map redaction in previews, and align with your security review.",
            ),
        ],
        "cta_p": "Describe your current CMS pain—model, migration, or governance—and we&rsquo;ll scope the smallest project that unblocks publishing.",
        "back_href": "services.html#content-cms",
        "back_label": "CMS offerings list",
    },
    {
        "file": "service-analytics-experimentation.html",
        "service_name": "Analytics & experimentation",
        "title": "Analytics &amp; Experimentation — CraftedPixel | GA4, GTM, Dashboards &amp; A/B Tests",
        "og_title": "Analytics, Tracking &amp; A/B Testing | CraftedPixel",
        "meta_desc": "Measurement plans, GA4 and GTM event taxonomy, executive dashboards, A/B testing with clear readouts, and privacy-conscious analytics setup. Make data useful for product decisions.",
        "crumb_last": "Analytics",
        "h1": "Analytics &amp; experimentation",
        "lede": "Event taxonomy, funnels, and experiments tied to decisions—not vanity dashboards that age in a shared drive.",
        "meta_row": [
            ("Engagements", "Audits to embedded"),
            ("Stack", "GA4 · GTM · Warehouse"),
            ("Output", "Specs + dashboards"),
        ],
        "jump": [
            ("#process-flow", "Process"),
            ("#measurement", "Plan"),
            ("#events", "Events"),
            ("#dashboards", "Dashboards"),
            ("#experimentation", "Tests"),
            ("#privacy", "Privacy"),
            ("#future", "Future"),
            ("#related-work", "Work"),
            ("#service-faq", "FAQ"),
        ],
        "intro_h": "How we plug in",
        "intro_lede": "We start from decisions you need weekly: funnel health, feature adoption, campaign efficiency—then reverse into events, dimensions, and governance so new releases don&rsquo;t silently break reporting.",
        "pills": [
            ("fa-list-check", "<strong>Measurement sprint</strong> — baseline audit, fix naming drift, ship a v1 plan."),
            ("fa-chart-column", "<strong>Dashboards</strong> — exec and squad views with agreed definitions."),
            ("fa-flask", "<strong>Experimentation</strong> — design, power, and readouts for product bets."),
        ],
        "flow_h": "From definitions to trusted readouts",
        "flow_lede": "Naming and QA before another custom dimension nobody trusts.",
        "flow_steps": [
            ("fa-bullseye", "Plan", "KPIs &amp; defs"),
            ("fa-tag", "Events", "Taxonomy + GTM"),
            ("fa-chart-pie", "Report", "Dashboards"),
            ("fa-vials", "Test", "A/B design"),
            ("fa-shield-halved", "Privacy", "Consent &amp; PII"),
        ],
        "flow_strip": ["GA4", "GTM", "BigQuery", "Looker", "Flags"],
        "sections": [
            {
                "id": "measurement",
                "num": "01",
                "title": "Measurement plans",
                "aria": "sd-analytics-mp-title",
                "tag": "Goals, KPIs, segments, and definitions of &ldquo;active&rdquo; that finance, product, and marketing can cite without a 30-minute debate.",
                "p1": "We document north-star and guardrail metrics, map them to events and dimensions, and flag gaps where instrumentation doesn&rsquo;t exist yet.",
                "p2": "Plans include data freshness expectations and known blind spots (e.g., ad blockers, offline)—so leaders don&rsquo;t overfit noisy charts.",
                "outs": [
                    "Measurement plan doc (living template)",
                    "Event / dimension dictionary v1",
                    "Stakeholder sign-off checklist",
                    "QA scenarios for releases",
                ],
                "note": "Every team has a different definition of conversion, or board reporting broke after GA4 migration.",
            },
            {
                "id": "events",
                "num": "02",
                "title": "Event taxonomy &amp; tracking",
                "aria": "sd-analytics-ev-title",
                "tag": "GA4, GTM (or tag manager of choice), and server-side options when client reliability matters—tested with Tag Assistant and real sessions.",
                "p1": "We use a consistent naming convention, version breaking changes, and regression tests on key flows after each deploy.",
                "p2": "When BigQuery or warehouse export is in play, we document schema and partitioning so analysts aren&rsquo;t stuck in UI limits.",
                "outs": [
                    "GTM container export or change log",
                    "GA4 custom definitions list",
                    "Debug / staging validation notes",
                    "Developer implementation tickets",
                ],
                "note": "Marketing can&rsquo;t trust attribution, or releases keep zeroing out key events.",
            },
            {
                "id": "dashboards",
                "num": "03",
                "title": "Dashboards &amp; reporting",
                "aria": "sd-analytics-dash-title",
                "tag": "Executive roll-ups and squad-level views with filters that match how you actually segment customers—not 40 tabs nobody opens.",
                "p1": "We prototype in Looker Studio, Metabase, or your BI tool of choice, then lock calculated fields to the measurement dictionary.",
                "p2": "Annotations for campaigns, releases, and incidents are built in so spikes have context six months later.",
                "outs": [
                    "Dashboard set with view personas",
                    "Refresh cadence &amp; owner roster",
                    "Export / slide snapshot workflow",
                    "Training for self-serve tweaks",
                ],
                "note": "Leadership wants one trustworthy weekly email; ops needs drill-down without exporting CSV chaos.",
            },
            {
                "id": "experimentation",
                "num": "04",
                "title": "A/B testing &amp; feature flags",
                "aria": "sd-analytics-exp-title",
                "tag": "Hypothesis, power, randomization checks, and readouts that connect to ship/no-ship decisions—even when results are flat.",
                "p1": "We align on primary metric, guardrails, and minimum detectable effect before flipping traffic. Feature flags tie to the same event taxonomy.",
                "p2": "Post-test summaries include segments to investigate and whether to iterate or revert—avoiding endless multivariate sprawl.",
                "outs": [
                    "Experiment design template",
                    "Instrumentation checklist per test",
                    "Result memo format for stakeholders",
                    "Integration notes for your flag vendor",
                ],
                "note": "Product bets need evidence, or your flag tool is on but nobody trusts the numbers.",
            },
            {
                "id": "privacy",
                "num": "05",
                "title": "Privacy-conscious setup",
                "aria": "sd-analytics-priv-title",
                "tag": "Consent modes, PII boundaries, data retention, and regional considerations—documented so legal sign-off doesn&rsquo;t freeze every tag change.",
                "p1": "We map which tags fire pre/post consent, redact fields at collection where possible, and separate marketing IDs from product analytics where needed.",
                "p2": "DSAR and deletion implications are noted for warehouse tables—not an afterthought when GDPR mail arrives.",
                "outs": [
                    "Tag / consent matrix",
                    "PII inventory for analytics payloads",
                    "Retention recommendations",
                    "Change review checklist for new trackers",
                ],
                "note": "You operate in regulated industries or multiple regions with different consent defaults.",
            },
        ],
        "quote": (
            "We finally stopped arguing about event names in every roadmap meeting—the dictionary is the source of truth.",
            "Taylor N.",
            "Head of Product, Consumer app",
        ),
        "future_cards": [
            ("Piloting", "Warehouse-first KPIs", "Single metrics layer in BigQuery feeding GA4 and BI without drift."),
            ("Exploring", "Experiment pre-mortems", "Structured risk review before expensive traffic splits."),
            ("Coming soon", "Privacy sandbox readiness", "Chrome Topics / attribution API monitoring playbook."),
            ("Exploring", "Cohort health automation", "Early warning on activation metrics with Slack hooks."),
        ],
        "related_lede": "Work where measurement and conversion discipline showed up in results.",
        "related_cards": [
            {
                "href": "index.html#case-luma",
                "img": IMG_LUMA,
                "title": "Luma — conversion analytics",
                "desc": "Funnel and merchandising with <strong>measurable CVR lift</strong>.",
            },
            {
                "href": "index.html#case-mero",
                "img": IMG_MERO,
                "title": "Mero — product metrics",
                "desc": "Ship-fast engagement with expense volume tracked post-launch.",
            },
        ],
        "cadence_lede": "Typical analytics hardening cadence alongside your release train.",
        "cadence_w1": [
            "Access: GA4, GTM, product DB (as allowed)",
            "Baseline audit &amp; broken event list",
            "Workshop on decisions dashboards must support",
        ],
        "cadence_w2": [
            "Ship taxonomy v1 + GTM changes in staging",
            "QA pass on top 5 flows",
            "Dashboard v1 + review with stakeholders",
        ],
        "cadence_need": [
            "Admin access or shared GTM workspace",
            "List of regulated data categories",
            "Feature flag / experiment tool (if any)",
            "Owner for ongoing dictionary updates",
        ],
        "fit_p": "If you don&rsquo;t have stable instrumentation yet, fixing SEO or CMS content before heavy experimentation may be higher leverage.",
        "fit_links": [
            ("service-seo-growth.html", "SEO &amp; growth — organic measurement complements product analytics"),
            ("service-web-development.html", "Web development — server-side tagging and performance for reliable collection"),
            ("service-content-cms.html", "Content &amp; CMS — campaign UTM discipline and landing structure"),
        ],
        "faq_topic": "Analytics &amp; experimentation",
        "faq_intro": "Tooling, access, and how we keep reporting trustworthy after we leave.",
        "faq_items": [
            (
                "Can you work in our existing GA4 property?",
                "Yes. We prefer dedicated testing views or staging GTM where possible, then promote with change logs.",
            ),
            (
                "Do you replace our BI team?",
                "No—we make definitions and pipelines reliable so internal analysts spend time on insight, not firefighting broken events.",
            ),
            (
                "What about server-side GTM?",
                "We implement when client reliability or ad-block resilience justifies ops cost—documenting hosting and failover.",
            ),
            (
                "How do you handle mobile apps?",
                "We coordinate with your SDK owners (Segment, Firebase, etc.) so mobile and web events align in the dictionary.",
            ),
            (
                "What&rsquo;s included in experiment analysis?",
                "Power check, sanity metrics, segment slices we pre-register, and a written recommendation—flat results are still valuable learning.",
            ),
        ],
        "cta_p": "Tell us what decision is blocked on data—funnel, feature adoption, or campaign ROI—and we&rsquo;ll propose measurement or test design accordingly.",
        "back_href": "services.html#analytics-experimentation",
        "back_label": "Analytics offerings list",
    },
]
